version: '3.7'
services:

  auth-database-dev:
    image: postgres:latest
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    hostname:
      localhost
    ports:
      - '6116:5432'
    container_name: "auth-db-dev"
